version: '3.5'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
  app:
    build: .
    ports:
      - 8888:80
    volumes:
      - ./app:/var/www/app
      - ./public:/var/www/public
    depends_on:
      - db

volumes:
  db:
